image: nfnty/arch-devel:latest

variables:
  REPONAME: "archlinux-overlay"
  REPODIR: "$CI_PROJECT_DIR"

before_script:
  - pacman -Syu --noconfirm
  - "echo 'nobody ALL=(ALL) NOPASSWD: /usr/bin/pacman' >> /etc/sudoers"
  
build_repo:
  script:
    - sudo -u nobody -E ./.build.sh
    - ./.deploy.sh

    # pacman expects files without tar.xz prefix
    - mv --force $REPONAME.db.tar.xz $REPONAME.db
    - mv --force $REPONAME.files.tar.xz $REPONAME.files
  artifacts:
    paths:
      - "$REPONAME.db"
      - "$REPONAME.files"
      - "*.pkg.tar.xz"
  