image: nfnty/arch-devel:latest

variables:
  REPONAME: "archlinux-overlay"
  REPODIR: "$CI_PROJECT_DIR"

  
before_script:
  - pacman -Syu --noconfirm

  # flex 2.6.3 is severly broken / incompatible
  # see e.g. https://github.com/westes/flex/issues/162
  - "if [[ $( pacman -Q flex ) == *2.6.3* ]]; then
       curl https://archive.archlinux.org/packages/f/flex/flex-2.6.1-1-x86_64.pkg.tar.xz -o /tmp/flex-2.6.1-1-x86_64.pkg.tar.xz;
       pacman --noconfirm -U /tmp/flex-2.6.1-1-x86_64.pkg.tar.xz;
     fi"
  
  # The repository build script is run by user 'nobody'. The build scripts needs
  # to install dependencies using pacman. This requires root permissions.
  # (Note: the build script itself can't be run as root, as makepkg would
  # complain)
  - "echo 'nobody ALL=(ALL) NOPASSWD: /usr/bin/pacman' >> /etc/sudoers"
  
  # a writable home-directory is needed by import-validpgpkeys.sh
  - mkdir -p /home/nobody && chown -R nobody /home/nobody
  - usermod -d /home/nobody nobody
  
  # import pgp keys flagged as valid
  - sudo -u nobody -E -H .build-bin/import-validpgpkeys.sh
  
  
build_repo:
  script:
    # the build script can't be run as root, as makepkg would complain...
    - sudo -u nobody -E -H .build-bin/build.sh
    
    # prepare & publish repository index
    # -> pacman expects files without tar.xz prefix,
    #    replace existing symlinks for artifacts upload (only)
    #    keep symlinks when building locally without artifact upload
    - sudo -u nobody -E -H .build-bin/deploy.sh
    - "if [[ -n $CI_PROJECT_URL ]]; then
         mv --force $REPONAME.db.tar.xz $REPONAME.db; fi"
    - "if [[ -n $CI_PROJECT_URL ]]; then
         mv --force $REPONAME.files.tar.xz $REPONAME.files; fi"
    
  artifacts:
    # expire artifacts per default - the gitlab web frontend can be used to keep
    # artifacts of interest for an unlimited time
    expire_in: 1 week
    paths:
      - "$REPONAME.db"
      - "$REPONAME.files"
      - "*.pkg.tar.xz"
  
